baseurl = "/"
languageCode = "en-us"
title = "Golden Thread Productions"

[menu]
	[[menu.primary]]
	identifier = "season"
	name = "SEASON"
	url = "/season"
	weight = 1

		[[menu.primary]]
		parent = "season"
		identifier = "reorient-2019"
		name = "ReOrient 2019"
		url = "/productions/reorient-2019"
		weight = 11

		[[menu.primary]]
		parent = "season"
		identifier = "leila"
		name = "Leila’s Quest For Flight"
		url = "/productions/leila"
		weight = 12

		[[menu.primary]]
		parent = "season"
		identifier = "obam-2019"
		name = "On Behalf of All Muslims"
		url = "/productions/obam-2019"
		weight = 13

		[[menu.primary]]
		parent = "season"
		identifier = "scenes-from-71-years"
		name = "Scenes From 71* Years"
		url = "/productions/scenes-from-71-years"
		weight = 14

		[[menu.primary]]
		parent = "season"
		identifier = "wdtws-2019"
		name = "What Do the Women Say?"
		url = "/productions/wdtws-2019"
		weight = 15

	[[menu.primary]]
	identifier = "about"
	name = "ABOUT"
	url = "/about"
	weight = 2
		
		[[menu.primary]]
		parent = "about"
		identifier = "people"
		name = "People"
		url = "/about/people"
		weight = 21

		[[menu.primary]]
		parent = "about"
		identifier = "history"
		name = "History"
		url = "/about/history"
		weight = 22

		[[menu.primary]]
		parent = "about"
		identifier = "past-productions"
		name = "Past Productions"
		url = "/productions"
		weight = 23

		[[menu.primary]]
		parent = "about"
		identifier = "donors"
		name = "Donors"
		url = "/about/donors"
		weight = 24

		[[menu.primary]]
		parent = "about"
		identifier = "champions"
		name = "20 Champions"
		url = "/about/champions"
		weight = 25

		[[menu.primary]]
		parent = "about"
		identifier = "bill-of-rights"
		name = "Bill of Rights"
		url = "/about/bill-of-rights"
		weight = 26

	[[menu.primary]]
	identifier = "programs"
	name = "PROGRAMS"
	url = "/programs"
	weight = 3

		[[menu.primary]]
		parent = "programs"
		identifier = "fairytale-players"
		name = "Fairytale Players"
		url = "/programs/fairytale-players"
		weight = 31

		[[menu.primary]]
		parent = "programs"
		identifier = "reorient"
		name = "ReOrient Festival"
		url = "/programs/reorient"
		weight = 32

		[[menu.primary]]
		parent = "programs"
		identifier = "new-plays"
		name = "New Play Development"
		url = "/programs/new-plays"
		weight = 33

		[[menu.primary]]
		parent = "programs"
		identifier = "new-threads"
		name = "New Threads Reading Series"
		url = "/programs/new-threads"
		weight = 34

		[[menu.primary]]
		parent = "programs"
		identifier = "what-do-the-women-say"
		name = "What do the Women Say?"
		url = "/programs/what-do-the-women-say"
		weight = 35

	[[menu.primary]]
	identifier = "get-involved"
	name = "GET INVOLVED"
	url = "/get-involved"
	weight = 4

		[[menu.primary]]
		parent = "get-involved"
		identifier = "donate"
		name = "Make a Donation"
		url = "/donate"
		weight = 41

		[[menu.primary]]
		parent = "get-involved"
		identifier = "volunteer"
		name = "Volunteer"
		url = "/get-involved/volunteer"
		weight = 42


[secondary-menu]
	[[menu.secondary]]
	identifier = "tickets"
	name = "BUY TICKETS"
	url = "/tickets"
	weight = 1

	[[menu.secondary]]
	identifier = "donate"
	name = "DONATE NOW"
	url = "/donate"
	weight = 2

	[[menu.secondary]]
	identifier = "book"
	name = "BOOK A SHOW"
	url = "/programs/fairytale-players"
	weight = 3

