backend:
  name: git-gateway
display_url: https://goldenthread.org
publish_mode: editorial_workflow
media_library:
  name: uploadcare
  config:
    publicKey: 27bd1f32452db346e082
    data-tabs: "file url gdrive dropbox facebook"
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "production" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Productions" # Used in the UI, ie.: "New Post"
    label_singular: "Production"
    folder: "site/content/productions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Eyebrow", name: "pre", widget: "string", required: false}
      - {label: "Season", name: "season", widget: "number", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Start Date", name: "start", widget: "datetime", required: false}
      - {label: "End Date", name: "end", widget: "datetime", required: false}
      - {label: "Heading", name: "heading", widget: "string", required: false}
      - {label: "Intro", name: "description", widget: "markdown", required: false}
      - {label: "Header Image", name: "background", widget: "image", required: false}
      - {label: "Title Image", name: "titleimage", widget: "image", required: false}
      - label: Videos
        name: videos
        widget: list
        fields:
          - {label: YouTube ID, name: id, widget: string, required: false}
      - {label: "Writer", name: "writer", widget: "string", required: false}
      - {label: "Director", name: "director", widget: "string", required: false}
      - {label: "Featuring", name: "featuring", widget: "string", required: false}
      - {label: "Translator", name: "translator", widget: "string", required: false}
      - {label: "Dramaturg", name: "dramaturg", widget: "string", required: false}
      - {label: "Musical Director", name: "musicaldirector", widget: "string", required: false}
      - {label: "Additional Credit", name: "additional", widget: "string", required: false}
      - {label: "Stage", name: "stage", widget: "string", required: false}
      - {label: "Address", name: "address", widget: "string", required: false}
      - {label: "Visit Link", name: "visitlink", widget: "string", required: false}
      - {label: "Ticket Link", name: "ticketlink", widget: "string", required: false}
      - {label: "Ticket Info", name: "ticketinfo", widget: "string", required: false}
      - {label: "Awards Image", name: "awardsimage", widget: "image", required: false}
      - {label: "Awards Text", name: "awards", widget: "string", required: false}
      - {label: "External Link", name: "externallink", widget: "string", required: false}
      - {label: "Misc. Text", name: "misc", widget: "text", required: false}
      - label: "Lists"
        name: "lists"
        widget: "list"
        fields:
          - {label: "Heading", name: "heading", widget: "string", required: false}
          - label: Items
            name: items
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Eyebrow", name: "pre", widget: "string", required: false}
              - {label: "Subtitle", name: "subtitle", widget: "markdown", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
              - {label: "Call to action", name: "cta", widget: "string", required: false}
              - {label: "Link", name: "link", widget: "string", required: false}
      - label: "Grids"
        name: "grids"
        widget: "list"
        fields:
          - {label: "Heading", name: "heading", widget: "string", required: false}
          - label: Items
            name: items
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Eyebrow", name: "pre", widget: "string", required: false}
              - {label: "Subtitle", name: "subtitle", widget: "markdown", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
              - {label: "Call to action", name: "cta", widget: "string", required: false}
              - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Cast and Crew
        name: cast
        widget: object
        required: false
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - label: Bios
            name: items
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string", required: false}
              - {label: "Credit", name: "credit", widget: "string", required: false}
              - {label: Image, name: image, widget: image, required: false}
              - {label: "Bio", name: "bio", widget: "markdown", required: false}
              - {label: "Alt. Text", name: "text", widget: "markdown", required: false}
      - label: Photo Gallery
        name: photos
        widget: object
        required: false
        fields: 
          - {label: "Heading", name: "heading", widget: "string"}
          - label: Images
            name: items
            widget: list
            fields:
              - {label: Image, name: image, widget: image, required: false}
      - label: Sponsors/Bottom
        name: bottom
        widget: object
        fields:
          - {label: "Heading", name: "heading", widget: "string", required: false}
          - {label: "Text", name: "text", widget: "markdown", required: false}
          - label: Logos
            name: logos
            widget: list
            fields:
              - {label: Image, name: image, widget: image, required: false}