backend:
  name: git-gateway
publish_mode: editorial_workflow
media_library:
  name: uploadcare
  config:
    publicKey: 27bd1f32452db346e082
    data-tabs: "file url gdrive dropbox facebook"
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "production" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Productions" # Used in the UI, ie.: "New Post"
    label_singular: "Production"
    folder: "site/content/productions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Eyebrow", name: "pre", widget: "string", required: false}
      - {label: "Season", name: "season", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Start Date", name: "start", widget: "datetime", required: false}
      - {label: "End Date", name: "end", widget: "datetime", required: false}
      - {label: "Heading", name: "heading", widget: "string", required: false}
      - {label: "Intro", name: "description", widget: "markdown", required: false}
      - {label: "Header Image", name: "background", widget: "image", required: false}
      - {label: "Title Image", name: "titleimage", widget: "image", required: false}
      - label: Videos
        name: videos
        widget: list
        fields:
          - {label: YouTube ID, name: id, widget: string, required: false}
      - {label: "Writer", name: "writer", widget: "string", required: false}
      - {label: "Director", name: "director", widget: "string", required: false}
      - {label: "Featuring", name: "featuring", widget: "string", required: false}
      - {label: "Additional Credit", name: "additional", widget: "string", required: false}
      - {label: "Stage", name: "stage", widget: "string", required: false}
      - {label: "Address", name: "address", widget: "string", required: false}
      - {label: "Ticket Link", name: "ticketlink", widget: "string", required: false}
      - {label: "Ticket Info", name: "ticketinfo", widget: "string", required: false}
      - {label: "Awards Image", name: "awardsimage", widget: "image", required: false}
      - {label: "Awards Text", name: "awards", widget: "string", required: false}
      - {label: "Misc. Text", name: "misc", widget: "text", required: false}
      - label: "Lists"
        name: "lists"
        widget: "list"
        fields:
          - {label: "Heading", name: "heading", widget: "string", required: false}
          - label: Items
            name: items
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Eyebrow", name: "pre", widget: "string", required: false}
              - {label: "Subtitle", name: "subtitle", widget: "markdown", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
              - {label: "Call to action", name: "cta", widget: "string", required: false}
              - {label: "Link", name: "link", widget: "string", required: false}
      - label: "Grids"
        name: "grids"
        widget: "list"
        fields:
          - {label: "Heading", name: "heading", widget: "string", required: false}
          - label: Items
            name: items
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Eyebrow", name: "pre", widget: "string", required: false}
              - {label: "Subtitle", name: "subtitle", widget: "markdown", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
              - {label: "Call to action", name: "cta", widget: "string", required: false}
              - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Cast and Crew
        name: cast
        widget: object
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - label: Bios
            name: items
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string", required: false}
              - {label: "Credit", name: "credit", widget: "string", required: false}
              - {label: Image, name: image, widget: image, required: false}
              - {label: "Bio", name: "bio", widget: "markdown", required: false}
              - {label: "Alt. Text", name: "text", widget: "markdown", required: false}
      - label: Photo Gallery
        name: photos
        widget: object
        fields: 
          - {label: "Heading", name: "heading", widget: "string"}
          - label: Images
            name: items
            widget: list
            fields:
              - {label: Image, name: image, widget: image, required: false}
      - label: Sponsors/Bottom
        name: bottom
        widget: object
        fields:
          - {label: "Heading", name: "heading", widget: "string", required: false}
          - {label: "Text", name: "text", widget: "markdown", required: false}
          - label: Logos
            name: logos
            widget: list
            fields:
              - {label: Image, name: image, widget: image, required: false}
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    label_singular: "Post"
    folder: "site/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text", required: false}
      - {label: "Header Image", name: "background", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Headline, name: headline, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Image, name: background, widget: image}
          - {label: Call to action, name: cta, widget: string}
          - {label: Link, name: link, widget: string}
          - label: Blurbs
            name: items
            widget: list
            fields:
              - {label: Title, name: subtitle, widget: markdown}
              - {label: Text, name: text, widget: markdown}
              - {label: Image, name: image, widget: image}
              - {label: Call to action, name: cta, widget: string}
              - {label: Link, name: link, widget: string}
      - file: "site/content/tickets/_index.md"
        label: "Tickets Page"
        name: "tickets"
        fields:
          - {label: Title, name: title, widget: string}
          - label: "Lists"
            name: "lists"
            widget: "list"
            fields:
              - {label: "Heading", name: "heading", widget: "string", required: false}
              - label: Items
                name: items
                widget: list
                fields:
                  - {label: "Title", name: "title", widget: "string", required: false}
                  - {label: "Eyebrow", name: "pre", widget: "string", required: false}
                  - {label: "Subtitle", name: "subtitle", widget: "markdown", required: false}
                  - {label: "Image", name: "image", widget: "image", required: false}
                  - {label: "Text", name: "text", widget: "markdown", required: false}
                  - {label: "Call to action", name: "cta", widget: "string", required: false}
                  - {label: "Link", name: "link", widget: "string", required: false}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/about/people/_index.md"
        label: "People Page"
        name: "people"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Staff
            name: staff
            widget: object
            fields: 
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text, required: false}
              - label: items
                name: items
                widget: list
                fields:
                  - {label: "Name", name: "name", widget: "string", required: false}
                  - {label: "Credit", name: "credit", widget: "string", required: false}
                  - {label: Image, name: image, widget: image, required: false}
                  - {label: "Bio", name: "bio", widget: "markdown", required: false}
          - label: Board of Trustees
            name: board
            widget: object
            fields: 
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text, required: false}
              - label: items
                name: items
                widget: list
                fields:
                  - {label: "Name", name: "name", widget: "string", required: false}
                  - {label: "Credit", name: "credit", widget: "string", required: false}
                  - {label: Image, name: image, widget: image, required: false}
                  - {label: "Bio", name: "bio", widget: "markdown", required: false}
          - label: Artists
            name: artists
            widget: object
            fields: 
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text, required: false}
              - label: items
                name: items
                widget: list
                fields:
                  - {label: "Name", name: "name", widget: "string", required: false}
                  - {label: "Credit", name: "credit", widget: "string", required: false}
                  - {label: Image, name: image, widget: image, required: false}
                  - {label: "Bio", name: "bio", widget: "markdown", required: false}
          - label: Advisory Board
            name: advisors
            widget: object
            fields: 
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text, required: false}
              - label: items
                name: items
                widget: list
                fields:
                  - {label: "Name", name: "name", widget: "string", required: false}
                  - {label: "Credit", name: "credit", widget: "string", required: false}
                  - {label: Image, name: image, widget: image, required: false}
                  - {label: "Bio", name: "bio", widget: "markdown", required: false}
      - file: "site/content/season/_index.md"
        label: "Season Page"
        name: "season"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text, required: false}
          - {label: "Header Image", name: "background", widget: "image", required: false}
          - label: "Lists"
            name: "lists"
            widget: "list"
            fields:
              - {label: "Heading", name: "heading", widget: "string", required: false}
              - label: Items
                name: items
                widget: list
                fields:
                  - {label: "Title", name: "title", widget: "string", required: false}
                  - {label: "Eyebrow", name: "pre", widget: "string", required: false}
                  - {label: "Subtitle", name: "subtitle", widget: "markdown", required: false}
                  - {label: "Image", name: "image", widget: "image", required: false}
                  - {label: "Text", name: "text", widget: "markdown", required: false}
                  - {label: "Call to action", name: "cta", widget: "string", required: false}
                  - {label: "Link", name: "link", widget: "string", required: false}
      - file: "site/content/about/donors/_index.md"
        label: "Donors Page"
        name: "donors"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text, required: false}
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Sidebar"
            name: sidebar
            widget: object
            fields: 
              - {label: "Heading", name: "heading", widget: "string", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
      - file: "site/content/get-involved/_index.md"
        label: "Get Involved Page"
        name: "get-involved"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text, required: false}
          - {label: Body, name: body, widget: markdown, required: false}
      - file: "site/content/get-involved/jobs/_index.md"
        label: "Jobs Page"
        name: "jobs"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Sidebar"
            name: sidebar
            widget: object
            fields: 
              - {label: "Heading", name: "heading", widget: "string", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
      - file: "site/content/get-involved/volunteer/_index.md"
        label: "Volunteer Page"
        name: "volunteer"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Sidebar"
            name: sidebar
            widget: object
            fields: 
              - {label: "Heading", name: "heading", widget: "string", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
      - file: "site/content/get-involved/auditions/_index.md"
        label: "Auditions Page"
        name: "auditions"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Sidebar"
            name: sidebar
            widget: object
            fields: 
              - {label: "Heading", name: "heading", widget: "string", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
      - file: "site/content/get-involved/submissions/_index.md"
        label: "Submissions Page"
        name: "submissions"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Sidebar"
            name: sidebar
            widget: object
            fields: 
              - {label: "Heading", name: "heading", widget: "string", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
      - file: "site/content/get-involved/internships/_index.md"
        label: "Internships Page"
        name: "internships"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Sidebar"
            name: sidebar
            widget: object
            fields: 
              - {label: "Heading", name: "heading", widget: "string", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
  # - name: settings
  #   label: Settings
  #   editor:
  #     preview: false
  #   files:
  #     - file: data/settings/nav.yml
  #       label: Navigation
  #       name: navigation
  #       fields:
  #         - label: Navigation
  #           name: nav_items
  #           widget: list
  #           fields:
  #             - {label: Label, name: label, widget: string}
  #             - {label: Path, name: path, widget: string}
      # - file: "site/content/products/_index.md"
      #   label: "Products Page"
      #   name: "products"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      # - file: "site/content/values/_index.md"
      #   label: "Values Page"
      #   name: "values"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - label: Values
      #       name: values
      #       widget: list
      #       fields:
      #         - {label: Heading, name: heading, widget: string}
      #         - {label: Text, name: text, widget: text}
      #         - {label: Image, name: imageUrl, widget: image}
